### ISSUE TITLE
HDF5 files should be placed in a new directory

### ISSUE THREAD

**Issue by xMestas** [Niemeyer-Research-Group/pyMARS#14]
Currently the HDF5 files produced by the simulation are placed in the same directory as the source code.    Should they get their own directory that is overwritten every time?  There own directory including the process id so that they all are maintained?  Or just be deleted entirely after the program finishes execution?  

The path that the files will be written to can be given as an argument to the Simulation constructor.  The simulations are created in helper.py.

**Comment by kyleniemeyer** [comment]
The data used for the reduction should not be automatically deleted when the program finishes, because you may want to run a reduction again for the same initial conditions but with some of the reduction options changed (different targets, error limit, method, etc.).

So I think a `data` or something folder should be created and used for these files; then, there should be an option when running the program to reuse that data (or perhaps default to reusing the data, and have a flag to remove old data.)
