### ISSUE TITLE
Woo boy is the `get_rates_drg` function ever slow :)

### ISSUE THREAD

**Issue by arghdos** [Niemeyer-Research-Group/pyMARS#48]
Using the Galway DME/CH4 model with:

```
python -m cProfile __main__.py -m work/galway.cti --method DRG --targets CH4 --error 1e-4 --conditions work/input.txt
```

The input conditions are stoichometric methane at 1 Atm and 1000 and 1200K.

The reduction spends ~97% (287.821 / 297.121) percent of it's time calculating the DRG coefficients!!!!!!!!!

```
Testing for starting threshold value
Threshold     Species in Mech      Error
         45160355 function calls (45150236 primitive calls) in 302.849 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
   ...
   1    0.000    0.000    0.000    0.000 drg.py:1(<module>)
   1    0.000    0.000  297.121  297.121 drg.py:142(run_drg)
   1    0.019    0.019    0.041    0.041 drg.py:19(trim_drg)
   1    0.000    0.000    0.041    0.041 drg.py:267(drg_loop_control)
   1  266.119  266.119  287.821  287.821 drg.py:336(get_rates_drg)
   1    0.000    0.000    0.000    0.000 drg.py:441(graph_search)
    ...
    1    3.126    3.126  300.247  300.247 pymars.py:14(pymars)
```

Various improvements:
- This method _really needs_ to be converted to updating of a numpy array for efficiency.  This is key.  String parsing is BAD.  Create a NxN numpy array (N = # of species) and use the species_index (this might be worth putting in a dict of gas.species_name->index) for indexing.
- Why the branched statement for `if reac_prod_rate > 0:` and `if reac_prod_rate < 0:`? Both branches do the same thing!

**Comment by kyleniemeyer** [comment]
Thanks @arghdos—we are in the process of doing some major refactoring of the code right now to clean it up and improve efficiency

**Comment by xMestas** [comment]
I think that one of the reasons this function is slow is the unnecessary loop on line 370.  I thought I removed this already, but I guess it never got merged into master.  I submitted at as a PR #50.

**Comment by kyleniemeyer** [comment]
It turns out that there were two issues in this function: 
1. the unnecessary outer loop over species (which not only meant the loop repeated n_species times, but also that the numerator and denominator of the r_AB calculation had the relevant terms added that many times), and
2. that species showing up in both the reactants and products (like N2) are getting terms counted from reactions in both directions—even where the overall stoichiometric coefficient is zero, meaning there should be no contribution.

My `refactor` branch, which has some changes based on @arghdos's suggestions in #49, fixes this, in additional to all of the other work. Interestingly, for a sample GRI Mech case, the reduction performance is worse using the "correct" DRG method than incorrect older code.
