### ISSUE TITLE
Consider consolidating required inputs to the yaml file

### ISSUE THREAD

**Issue by jcsutherland** [Niemeyer-Research-Group/pyMARS#57]
Presently, there are two places that required inputs reside: the command line and the input file.  This seems a bit fragmented.

Consider consolidating the _required_ inputs into the yaml file.  These include:

- `--model` 
- `--targets` and `retained_speces`
- `--method`
- `--error`

This would improve reproducibility since all of the required inputs would be contained in a single input file.  Then consider renaming `--conditions` or make the input file a required non-named argument.

**Comment by kyleniemeyer** [comment]
I struggled with the best way to handle this, but I think I agree that reduction inputs make sense in a YAML file, also including `--sensitivity_analysis`, `--sensitivity_type`, and `--upper_threshold`.

The remaining command-line options would be:
```
-h, --help:
   show this help message and exit
--path:
   Path to directory for writing files
--num_threads:
   Number of CPU cores to use for running simulations in parallel
--convert:
   Convert files between Cantera and Chemkin formats (.cti <=> .inp)
--thermo:
   thermodynamic data filename (only necessary for Chemkin files)
--transport:
   transport data filename (only necessary for Chemkin files)
```

with a new `--input` option for the reduction input YAML file, that includes the autoignition conditions list.

(`--thermo` and `--transport` make sense to me  as command-line inputs, since you would only need to use these once before you have a Cantera-format model to use.)
