### ISSUE TITLE
soln2ck Troe error

### ISSUE THREAD

**Issue by tsikes** [Niemeyer-Research-Group/pyMARS#73]
You guys have saved me so much work in writing soln2ck. I use it quite frequently and have made a few modifications to it. One bug that I think is critical for you to fix however is on line 367 of soln2ck. The line should read reaction.low_rate instead of reaction.high_rate. This error is detrimental for anyone that has a Troe type reaction in their mechanism.

**Comment by xMestas** [comment]
Hello, 

Sorry for the late reply.  Thank you for pointing this out.  I looked it over and I believe you are correct.  I created a pull request ( #74 ) so that Dr. Niemeyer can review this change.  I'm glad that you have found use out of this, and that you have been actively working on improving it yourself.  I encourage you to submit your other improvements as well.  I saw that you posted your updated file in another thread.  Maybe make a separate issue for the changes that you have made, or just create a pull request so we can more easily review those changes.  

Thanks,
Phillip
